all:
  hosts:
    worker1:
      ansible_host: 192.168.198.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
    worker2:
      ansible_host: 192.168.198.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
