- name: Install PHP packages including MySQLi extension
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php7.4
    - php7.4-mysql
  notify: restart apache

- name: Copy php.ini configuration file
  become: yes
  copy:
    src: php.ini
    dest: /etc/php/7.4/apache2/php.ini
  notify: restart apache

- name: restart apache
  become: yes
  service:
    name: apache2
    state: restarted



- name: "[INSTALL WORDPRESS] - check if exist"
  stat:
    path: "/var/www/html/wordpress/"
  register: check_wordpress

- name: "[INSTALL WORDPRESS] - download tar.gz"
  unarchive:
    src: "{{ wordpress_source }}"
    dest: "/var/www/html/"
    remote_src: yes
  when: check_wordpress.stat.exists == False 


- name: "[INSTALL WORDPRESS] - drop file default index.html"
  file:
    path: "/var/www/html/index.html"
    state: absent

- name: Start MySQL service
  service:
    name: mysql
    state: started


- name: "[INSTALL WORDPRESS] - check if exist"
  stat:
    path: "/var/www/html/wordpress/wp-config-sample.php"
  register: check_sample

- name: "[INSTALL WORDPRESS] - rename wp-config-sample.php"
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  when: check_sample.stat.exists == True


- name: "[INSTALL WORDPRESS] - modify wp-config.php"
  lineinfile:
    dest: "/var/www/html/wordpress/wp-config.php"
    regexp: "{{ item.search }}"
    line: "{{ item.new }}"
    backrefs: yes
  with_items:
    - {'search': '^(.*)database_name_here(.*)$', 'new': '\1{{ mysql_db }}\2'}
    - {'search': '^(.*)username_here(.*)$', 'new': '\1{{ mysql_user }}\2'}
    - {'search': '^(.*)password_here(.*)$', 'new': '\1{{ mysql_password }}\2'}
